camera:
  type: realsense
  intrin:
    fx: 645.060547
    fy: 644.257935
    cx: 649.562866
    cy: 373.498932
    distortion_model: 0
    distortion_coeffs:
      []
  extrin:
    -
      - 0.00860485621
      - -0.21989806
      - 0.975484908
      - -0.00505150529
    -
      - -0.999961734
      - -0.0033939057
      - 0.00805569999
      - -0.0279818624
    -
      - 0.00153927063
      - -0.975516975
      - -0.219918877
      - -0.0554900765
    -
      - 0
      - 0
      - 0
      - 1
  pitch_compensation: 0
  yaw_compensation: 0
  z_compensation: 0
detection_model:
  model_path: ./src/vision/model/best_orin_10.3.engine
  confidence_threshold: 0.2
  nms_threshold: 0.4
  classnames: [Ball, Goalpost, Person, LCross, TCross, XCross, PenaltyPoint, Opponent, BRMarker]
  post_process:
    single_ball_assumption: false
    confidence_thresholds:
      Ball: 0.4
      Goalpost: 0.4
      Person: 0.4
      LCross: 0.3
      TCross: 0.3
      XCross: 0.3
      PenaltyPoint: 0.3
      Opponent: 0.4
      BRMarker: 0.2
segmentation_model:
  model_path: ./src/vision/model/best_seg_orin_10.3.engine
  confidence_threshold: 0.3
  nms_threshold: 0.9
use_depth: true
ball_pose_estimator:
  use_depth: false
  radius: 0.109
  down_sample_leaf_size: 0.01
  cluster_distance_threshold: 0.01
  fitting_distance_threshold: 0.01
  minimum_cluster_size: 150
  filter_distance: 1.2
  check_ball_height: true
human_like_pose_estimator:
  use_depth: false
  down_sample_leaf_size: 0.01
  fitting_distance_threshold: 0.01
  statistic_outlier_multiplier: 0.01
field_marker_pose_estimator:
  refine: false
  line_segment_area_threshold: 75
calibration:
  sync_max_time_diff_ms: 1400
  offset:
    exclude_distance: 2.0
    zero_translation: true
    field_marker_path: ./src/vision/config/field.yaml
  handeye:
    calibration_time: 2025-10-25-11-18-36
    reprojection_error: 4.0379934623833185
misc:
  save_data_nonstationary: true